# Generated by Django 2.2.28 on 2023-07-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalForcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default='')),
                ('longitude', models.FloatField(default='')),
                ('temperature', models.FloatField(default='')),
                ('feels_like', models.CharField(default='', max_length=30, null=True)),
                ('temp_min', models.FloatField(default='')),
                ('temp_max', models.FloatField(default='')),
                ('pressure', models.FloatField(default='')),
                ('humidity', models.FloatField(default='')),
                ('visibility', models.IntegerField(default='')),
                ('weather_description', models.CharField(default='', max_length=100)),
                ('weather_icon', models.CharField(max_length=10)),
            ],
        ),
    ]
